Set up log in log out controllers
wyncode/c39_med_me pull request #4
Opened 2020-11-16 03:26 UTC by nunez2020

Close #3

2020-11-16 15:27 UTC, wkennedy8 commented on server/controllers/patients.js
> +    res.json(req.PdeletePatient);
where does `PdeletePatient` come from?

2020-11-16 15:27 UTC, wkennedy8 commented on server/controllers/patients.js
> +    await req.deletePatient.remove();
where does `deletePatient` come from?

2020-11-16 15:28 UTC, wkennedy8 commented on server/db/models/patient.js
> +  adress: {
typo, should be `address`

2020-11-16 15:28 UTC, wkennedy8 commented on server/db/models/patient.js
> +  order: [
should be `orders`

2020-11-16 20:55 UTC, wkennedy8 commented on server/controllers/patients.js
> +    const deletePatient = await deletePatient.findOne({ email });
`Patient` not `deletePatient`

2020-11-17 01:31 UTC, Stommy123 commented on package.json
>      "mongodb": "^3.6.2",
im not sure yo uneed `mongodb` as a dependency. You interact with your database entirely through `mongoose`

(I know this wasn't added with this PR just figured it might be a good chance to remove extra dependencies

2020-11-17 01:31 UTC, Stommy123 commented on server/app.js
> +  openRoutes = require('./routes/open/index');
you shouldn't need to specify `/index`. If you don't specify a file, it will default to `index.js`

2020-11-17 01:33 UTC, Stommy123 commented on server/controllers/users.js
> +      secure: process.env.NODE_ENV !== 'production' ? false : true
I think this can just be 
```
secure: process.env.NODE_ENV === 'production'
```
since the comparison will already return a boolean

2020-11-17 01:33 UTC, Stommy123 commented on server/controllers/users.js
> +      secure: process.env.NODE_ENV !== 'production' ? false : true
same as above

2020-11-17 01:34 UTC, Stommy123 commented on server/db/models/user.js
> +});
Do you have a task model?

2020-11-17 01:35 UTC, Stommy123 requested changes
Hey, looks pretty good. I just have one question about this block 
```
userSchema.virtual('tasks', {
  ref: 'Task',
  localField: '_id',
  foreignField: 'owner'
});
```

It might have been ported over from the todo app. We may want to repurpose it for your models as i don't see a `Task` model in your app

2020-11-17 01:43 UTC, nunez2020 commented on server/db/models/user.js
> +});
We did  imported from the to do app but have not given it purpose yet.

2020-11-17 02:29 UTC, Stommy123 approved these changes
LGTM

2020-11-17 02:54 UTC, christianmbonet approved these changes

2020-11-17 02:54 UTC, merged